---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Running the container
      docker_container:
        image: hasarangaprasad/test:2
        name: agent
