---
- hosts: all
  serial: 1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
  - name: Rm container
    docker_container:
      name: agent
      state: absent
      
  - name: Running the container
    docker_container:
      image: hasarangaprasad/test:latest
      name: agent
      ports: 80:8080


